const post = [
    {date: "11/12/20",
    title: "On the Street in Brooklyn",
    image : "https://ps-rtt-sei.herokuapp.com/fashionblog/blog-image-1.jpg",
    content: "orem ipsum dolor sit amet, consectetur adipisicing elit. Unde provident quis rerum a illum nostrum ratione, corporis dolorem. Eaque tempora porro, reprehenderit veritatis ab voluptatem asperiores consequatur omnis in praesentium. Lorem ipsum dolor sit amet consectetur adipisicing elit. Autem, earum amet quis consequatur obcaecati quibusdam laudantium incidunt ipsum est ex facilis excepturi sint labore, adipisci nam! Aliquid officiis temporibus neque. Lorem ipsum dolor sit amet consectetur adipisicing elit. Odio, provident, facilis blanditiis ut rerum ad ex quas iure, iusto quaerat explicabo nemo aperiam accusamus obcaecati autem fugiat repellendus quae dolor. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quod suscipit quaerat porro tempora ipsam ab consequuntur id, mollitia, explicabo dolorem rerum sint tempore? Cupiditate aut asperiores mollitia. Porro, ratione itaque! Lorem Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis est repudiandae atque eveniet ipsum fugit perferendis delectus quia illo hic, magnam quod earum commodi ratione! Ratione molestiae incidunt porro nihil."
    },
    {date: "11/11/20",
    title: "Vintage in Vogue",
    image : "https://ps-rtt-sei.herokuapp.com/fashionblog/blog-image-2.jpg",
    content: "orem ipsum dolor sit amet consectetur adipisicing elit. Iusto, quod numquam vel quo asperiores sit recusandae voluptatem quam quisquam minus nihil voluptate, expedita fugiat magnam officia eum labore. Incidunt, commodi. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nam repellendus, laboriosam natus libero officiis quam quaerat, nulla similique voluptas repudiandae aliquid, consequuntur cumque ratione quisquam. Quos reprehenderit hic velit quasi? Lorem ipsum dolor, sit amet consectetur adipisicing elit. Aut quibusdam sit quis tenetur a? Ducimus, assumenda maiores repellendus eum suscipit aliquid ipsum enim quibusdam, eaque eius odit nemo ab quisquam? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nam distinctio explicabo tempora tempore est a dignissimos rerum sint quasi molestiae assumenda quo quod alias debitis, nihil repellendus repellat, eveniet temporibus? Lorem ipsum, dolor sit amet consectetur adipisicing elit. Aspernatur labore, aperiam atque cumque dicta officia maiores adipisci vitae, porro perferendis eum voluptas voluptate temporibus ipsum molestias! Repellendus eos consequatur cupiditate! Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quod suscipit quaerat porro tempora ipsam ab consequuntur id, mollitia, explicabo dolorem rerum sint tempore? Cupiditate aut asperiores mollitia. Porro, ratione itaque! Lorem Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis est repudiandae atque eveniet ipsum fugit perferendis delectus quia illo hic, magnam quod earum commodi ratione! Ratione molestiae incidunt porro nihil."
    },
]

export default post